version: 2.1

jobs:
  test:
    docker:
      - image: cimg/python:3.7.8
      - image: minio/minio:RELEASE.2021-08-05T22-01-19Z
        environment:
          MINIO_ACCESS_KEY: AKIAIOSFODNN7EXAMPLE
          MINIO_SECRET_KEY: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
          MINIO_REGION: us-east-1
        entrypoint: sh
        command: ['-c', 'mkdir -p /data1 && mkdir -p /data2 && mkdir -p /data3 && mkdir -p /data4 && minio server /data{1...4}']
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install .
            pip install coverage
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - run:
          name: Run tests
          command: |
            set -exu
            ./cc-test-reporter before-build
            coverage run -m unittest
            coverage xml
            ./cc-test-reporter format-coverage
      - run:
          name: Upload coverage
          command: |
            set -exu
            ./cc-test-reporter sum-coverage coverage/*.json -p 1
            ./cc-test-reporter upload-coverage

workflows:
  test:
    jobs:
      - test
